# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(max_length=13)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=1)),
                ('num_documento', models.IntegerField()),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=13)),
                ('correo', models.CharField(max_length=200)),
                ('estatus', models.CharField(max_length=8)),
            ],
        ),
    ]
