# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 23:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle_factura',
            fields=[
                ('id_detalle_factura', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('precio_unit', models.DecimalField(decimal_places=2, max_digits=11)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('nro_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=11)),
                ('total', models.DecimalField(decimal_places=2, max_digits=11)),
                ('estatus', models.CharField(max_length=8)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.cliente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detalle_factura',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.factura'),
        ),
    ]
